### PR TITLE
Fix header row text overlapping search

### LINKED ISSUE #1808: Long Topic Title in Learn WordPress overlapping with the searchbox
## Description
Long topic title will cause overlapping display with the searchbox

## Step-by-step reproduction instructions
1. Go to this page https://learn.wordpress.org/topic/extending-wordpress/page/2/
2. See the Title and Search bar. https://share.getcloudapp.com/E0uL1Gw6

## Expected behaviour
It should display like this:- https://share.getcloudapp.com/Apug0BAQ

## Actual behaviour
But if the title is longer, the issue will happen. https://share.getcloudapp.com/geuPNv82

## Environment information
-I can replicate the issue in any browser, any OS, and mostly when in desktop view

## Additional Info
Simple fix is by decreasing the size of the .section-heading_title.h2

```
.section-heading_title.h2 {
    font-size: 2.0rem;
}
```
See https://share.getcloudapp.com/d5uD7rPb

### PR DESCRIPTION
**Pull request by adamwoodnz**
Extends #1829 
Closes #1808, #1813

Props: @cynthianorman 

Uses columns for heading section layouts where there is an element to the right of the title, to avoid wrapping when titles are long.

Removes CSS which negatively affects the alignment, and fixes the styling of the search input button.

### Lesson Plan archive

| Desktop | Tablet | Mobile |
|-|-|-|
| localhost_8888_topic_extending-wordpress_(Desktop) | localhost_8888_topic_extending-wordpress_(iPad) | localhost_8888_topic_extending-wordpress_(Samsung Galaxy S20 Ultra) |

### Home

| Desktop | Tablet | Mobile |
|-|-|-|
| localhost_8888_(Desktop) (1) | localhost_8888_(iPad) | localhost_8888_(Samsung Galaxy S20 Ultra) |

## Testing

Ideally all of the pages with templates changed should be checked at various screen sizes, you may need to create these pages or content for them

- http://localhost:8888/courses/
- http://localhost:8888/lesson-plans/
- http://localhost:8888/tutorials/
- http://localhost:8888/
- http://localhost:8888/content-calendar/
- http://localhost:8888/online-workshops/
- http://localhost:8888/my-courses/
- http://localhost:8888/?s=block
- http://localhost:8888/lesson-plan-series/my-series/ (probably need to create a Lesson Plan Series)
- http://localhost:8888/topic/extending-wordpress/
- Single Lesson Plan, Tutorial and Course

Check that the search input button is fixed and there is [no white appearing below or above it](https://github.com/WordPress/Learn/issues/1813)

### CODE REVIEW

File: wp-content/themes/pub/wporg-learn-2020/archive-course.php [hunk 1]
```diff
@@ -21,7 +21,7 @@
 <main id="main" class="site-main">
 	<section>
 		<div class="section-heading section-heading--with-space row align-middle between">
-			<?php the_archive_title( '<h1 class="section-heading_title h2">', '</h1>' ); ?>
+			<?php the_archive_title( '<h1 class="section-heading_title h2 col-8">', '</h1>' ); ?>
```
Comment (adamwoodnz) [inline wp-content/themes/pub/wporg-learn-2020/archive-course.php:24]: I've added this class to all the places we use this pattern and have an element on the right, to avoid the same breakage happening.

File: wp-content/themes/pub/wporg-learn-2020/page-content-calendar.php [hunk 2]
```diff
@@ -13,7 +13,7 @@
 
 	<main id="main" class="site-main">
 
-		<div class="row align-middle between section-heading section-heading--with-space">
```
Comment (adamwoodnz) [inline wp-content/themes/pub/wporg-learn-2020/page-content-calendar.php:16]: These classes aren't required on headings where there is no right element, and cause the title to be centered on small devices, which is not desirable.

File: wp-content/themes/pub/wporg-learn-2020/archive-course.php [hunk 3]
```diff
@@ -20,10 +20,12 @@
...
 	<section>
-		<div class="section-heading section-heading--with-space row align-middle between">
-			<?php the_archive_title( '<h1 class="section-heading_title h2">', '</h1>' ); ?>
+		<div class="section-heading section-heading--with-space row align-middle between gutters">
+			<?php the_archive_title( '<h1 class="section-heading_title h2 col-8">', '</h1>' ); ?>
 			<?php if ( is_user_logged_in() ) : ?>
-				<a class="section-heading_link" href="/my-courses/"><?php esc_html_e( 'My Courses', 'wporg-learn' ); ?></a>
+				<div class="col-4 row section-heading_links">
+					<a class="section-heading_link" href="/my-courses/"><?php esc_html_e( 'My Courses', 'wporg-learn' ); ?></a>
+				</div>
```
Comment (adamwoodnz) [inline wp-content/themes/pub/wporg-learn-2020/archive-course.php:28]: This pattern ensures there is space (`gutters`) between the elements both on desktop and smaller devices, and keeps the title left aligned, and any right elements right aligned within their column.

It's used for all the templates in this PR where the header uses this split layout.

**Comment by jonathanbossenger** [comment]
Thank you @adamwoodnz I'll make sure to do a more thorough review this time around.

**Review by jonathanbossenger — APPROVED** [review]
@adamwoodnz this all looks great in my testing. Thanks for wrangling this.
