### PR TITLE
Activate wporg-learn plugin at env setup

### LINKED ISSUE #2495: Feedback - Issue when installing "Setup 2024 version": Fatal is thrown
## Type of feedback
//dev

## Description
I'm seeing a fatal error while running `yarn run create`:
```php
Fatal error: Uncaught Error: Call to undefined function WPOrg_Learn\Sensei\get_my_courses_page_url() in /var/www/html/wp-content/themes/pub/wporg-learn-2024/functions.php:113
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(324): WordPressdotorg\Theme\Learn_2024\add_site_navigation_menus(Array)
#1 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /var/www/html/wp-content/mu-plugins/wporg-mu-plugins/mu-plugins/blocks/navigation/index.php(29): apply_filters('wporg_block_nav...', Array)
#3 /var/www/html/wp-includes/class-wp-hook.php(324): WordPressdotorg\MU_Plugins\Navigation_Block\init('')
#4 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-settings.php(700): do_action('init')
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('/var/www/html/w...')
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1 in /var/www/html/wp-content/themes/pub/wporg-learn-2024/functions.php on line 113
```

Looks like the **wporg-learn** plugin isn't active yet when the theme is activated.

The fatal occurs on https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/functions.php#L113C15-L113C38

### Proposed solution
I was able to make it work by adding `wporg-learn` at the end of:
https://github.com/WordPress/Learn/blob/trunk/bin/index.sh#L18

## Step-by-step reproduction instructions (optional)
Make sure to run `yarn run wp-env destroy` in case your installation has the plugin already active.

Follow the steps under "Setup 2024 version":
```
yarn
yarn run create
```

## Screenshots or screen recording (optional)
Screenshot 2024-06-03 at 10 43 04 PM

## Other information (optional)
Replicated on MacOS, with Node 18 and 20

### PR DESCRIPTION
**Pull request by freibergergarcia**
Activate the `wporg-learn` plugin at the environment setup, as it's a theme's dependency.

Fix the import content command by removing double quotes. 

Fixes #2495

### CODE REVIEW

File: bin/index.sh [hunk 1]
```diff
@@ -27,4 +27,4 @@ npm run wp-env run cli wp theme activate pub/wporg-learn-2024
 npm run wp-env run cli wp rewrite structure '/%postname%/'
 
 # Import content
-# npm run wp-env run cli "php bin/import-test-content.php"
+# npm run wp-env run cli php bin/import-test-content.php
```
Comment (adamwoodnz) [inline bin/index.sh]: This line is commented out. When I uncomment it the import works now without the quotes. Did you intend to comment it?

**Review by adamwoodnz — CHANGES_REQUESTED** [review]
Thanks for this!

I've tested and activating the plugin works, but the plugin also needs to be built.

In package.json we need to replace these lines:
```
"build": "yarn workspaces run build",
"create": "composer install && yarn setup:tools && yarn workspace wporg-learn-2024 run build && yarn run install:env",
"create:old": "composer install && yarn setup:tools && yarn workspaces run build && yarn run install:env:old",
```
with
```
"build": "yarn workspace wporg-learn-2024 run build && yarn workspace wporg-learn-plugin run build",
"build:old": "yarn workspace wporg-learn-theme run build && yarn workspace wporg-learn-plugin run build",
"create": "composer install && yarn setup:tools && yarn build && yarn run install:env",
"create:old": "composer install && yarn setup:tools && yarn build:old && yarn run install:env:old",
```
Could you please try that?

File: bin/index.sh (hunk 1 above)
Comment (freibergergarcia) [reply bin/index.sh]: I thought that it was intentionally left uncommented. I made the changes to the build process and uncommented the import command.

I'm new to the project, so I'm unsure, but it looks like the build didn't work as expected.

The courses have been imported to the local database, I can see Tutorials and Lesson Plans, but the front end looks like this:

localhost:8888
Screenshot 2024-06-06 at 7 26 46 AM

localhost:8888/tutorials
Screenshot 2024-06-06 at 7 47 49 AM

I suppose it should match: https://learn.wordpress.org/tutorials/?

I also looked at the [build workflow](https://github.com/WordPress/Learn/blob/trunk/.github/workflows/build.yml) and tried it out but had no luck. Any ideas?

Comment (adamwoodnz) [reply bin/index.sh]: No that's pretty much as expected. The theme is very much a work in progress; the 'No learning pathways found' message needs aligning, and there will be no Tutorials moving forward, so that is the default archive template you're seeing there. We can update the content import at some point to drop the out of date content and add some Lessons and Courses.

Thanks again for your help, I'll do a final test and get this merged.

**Review by adamwoodnz — APPROVED** [review]
