### PR TITLE
Fix browser titles

### LINKED ISSUE #2603: Browser titles incomplete
### Summary

Browser titles on some parts of the site are incomplete.

### Issue

On some parts of the site, the `<title>` tag - which appears in browser tabs, among other places, is incomplete.

Example:

https://learn.wordpress.org/level/beginner/page/7/?wporg_lesson_level=all&post_type=lesson

In this view the title tag is just `| Learn WordPress` 

`<title> | Learn WordPress </title>` 

### Expected

There should be some text before the pipe and site title, for example:

`Lessons | Learn WordPress` or `Lessons | Page 7 | Learn WordPress`

### Discovery 

Discovered while navigating the Lessons archives and testing filters.

### PR DESCRIPTION
**Pull request by outdoor2kode**
Fixes #2603

This PR fixes the site title. Below are screenshots of various pages. If there are any titles that need adjustments, please leave messages in the comments. Thanks.

| | **Screenshot** |
| - | - |
| **Homepage** | Screenshot 2024-07-15 at 06 33 15 |
| **Course** | Screenshot 2024-07-15 at 06 29 56 |
| **Single Course** | Screenshot 2024-07-15 at 06 31 39 |
| **Lesson** | Screenshot 2024-07-15 at 06 30 08 |
| **Single Lesson** | Screenshot 2024-07-15 at 06 32 30 |
| **Learning pathway** | Screenshot 2024-07-15 at 06 30 26 |
| **Learning pathway** | Screenshot 2024-07-15 at 06 30 39 |
| **Singe Page** | Screenshot 2024-07-15 at 06 30 57 |
| **Singe Page** | Screenshot 2024-07-15 at 06 31 09 |
| **Pagination** | Screenshot 2024-07-15 at 06 32 51 |

### CODE REVIEW

File: wp-content/themes/pub/wporg-learn-2024/inc/head.php [hunk 1]
```diff
@@ -0,0 +1,59 @@
+<?php
+
```
Comment (adamwoodnz) [inline wp-content/themes/pub/wporg-learn-2024/inc/head.php:7]: Add a namespace?
```suggestion

namespace WordPressdotorg\Theme\Learn_2024\Head;

```

File: wp-content/themes/pub/wporg-learn-2024/inc/head.php [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+/**
+ * Filters document title to add context based on what is being viewed.
+ *
+ * @param array $parts The document title parts.
+ * @return array The document title parts.
+ */
+function document_title( $parts ) {
+	global $wp_query;
+
+	$parts['site']  = __( 'Learn WordPress', 'wporg-learn' );
```
Comment (adamwoodnz) [inline wp-content/themes/pub/wporg-learn-2024/inc/head.php]: It seems we usually finish with the domain, eg.

| Main | Dev Resources | Patterns |
|--------|--------|--------|
| Screenshot 2024-07-15 at 4 19 47 PM | Screenshot 2024-07-15 at 4 16 13 PM | Screenshot 2024-07-15 at 4 17 17 PM | 

```suggestion
	$parts['site']  = __( 'Learn.WordPress.org', 'wporg-learn' );
```

File: wp-content/themes/pub/wporg-learn-2024/inc/head.php [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	$post_type      = get_query_var( 'post_type' );
+	$sep            = '–';
+
+	if ( is_front_page() ) {
+		$parts['title'] = 'There\'s always more to learn';
```
Comment (adamwoodnz) [inline wp-content/themes/pub/wporg-learn-2024/inc/head.php]: Should this use the site tagline to make it configurable? Or is that not translatable...

Screenshot 2024-07-15 at 4 27 09 PM

**Review by adamwoodnz — COMMENTED** [review]
Works for me, couple of comments inline

File: wp-content/themes/pub/wporg-learn-2024/inc/head.php (hunk 1 above)
Comment (outdoor2kode) [reply wp-content/themes/pub/wporg-learn-2024/inc/head.php:7]: d2a29b5

File: wp-content/themes/pub/wporg-learn-2024/inc/head.php (hunk 2 above)
Comment (outdoor2kode) [reply wp-content/themes/pub/wporg-learn-2024/inc/head.php]: I originally used Learn.WordPress.org, but then I decided to follow the ticket description first back then. @kathrynwp, can you help make the final confirmation for this, thanks.

Changed back for now 7ad5444

File: wp-content/themes/pub/wporg-learn-2024/inc/head.php (hunk 3 above)
Comment (outdoor2kode) [reply wp-content/themes/pub/wporg-learn-2024/inc/head.php]: Yeah, I'm not sure about the translation, which I think would just follow the set tagline, won't change with different languages. I noticed the [developer](https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/inc/head.php#L38) specified it in this way, so I wrote one here. In this case, if the tagline has content, it will extend to `There’s always more to learn | Tagline | Learn.WordPress.org`

Alternatively, we can completely follow the site title and tagline settings and not hardcode it, meaning we can remove the front page condition here. This way, we would get `Site title | Tagline | Learn.WordPress.org`

image
image

Comment (outdoor2kode) [reply wp-content/themes/pub/wporg-learn-2024/inc/head.php]: Removed the front page check for now: b348a33

image

**Review by adamwoodnz — APPROVED** [review]
LGTM :shipit:
